tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/dupes"
tap "neovim/neovim"
tap 'universal-ctags/universal-ctags'
tap 'ewilliam/booze'

# Ruby
brew "chruby", args: ["HEAD"]
brew "chruby-fish", args: ["HEAD"]
brew "ruby-install"
cask "rubymotion"

# Python
brew "python"
brew "python3"

# Javascript
brew "node"
brew "nvm"

# Git
brew "git"
brew "heroku-toolbelt"
brew "hub"
brew "tig"

# Editor
brew "macvim", args: ["custom-icons", "override-system-vim", "with-lua", "with-luajit"]
brew "neovim", args: ["HEAD"]
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
cask "atom"
cask "mou"
cask "nvalt"
cask "libreoffice"

# Shell
brew "fish"
brew "mobile-shell"
brew "reattach-to-user-namespace"
brew "ssh-copy-id"
brew "thefuck"
brew "tmux"
cask "iterm2-beta"

# Database
brew "postgresql"
brew "sqlite"
cask "postico"
cask "sequel-pro"

# Search
brew "fzf"
brew "peco"
brew "sift"

# Dev tools
brew "imagemagick"
brew "openssl"
cask "cyberduck"
cask "dockertoolbox"
cask "postman"
cask "virtualbox"

# Download
brew "wget"
cask "transmission"

# Mutt
brew "neomutt/homebrew-neomutt/neomutt", args: ["with-sidebar-patch", "with-notmuch-patch", "with-gpgme"]
brew "notmuch"
brew "msmtp"
brew "offlineimap"
brew "urlview"
brew "w3m"

# Media
brew "newsbeuter"
brew "pianobar"
cask "kodi"
cask "vlc"

# Browser
cask "google-chrome"
cask "firefox"

# Communication
brew "weechat"
cask "adium"
cask "slack"

# File sharing
cask "dropbox"
cask "google-drive"

# Games
cask "openemu"
cask "steam"

# Misc
brew "mas"
brew "unrar"
cask "appcleaner"
cask "clamxav"
cask "flux"
cask "focus"
cask "hammerspoon"
cask "meteorologist"
cask "karabiner"
cask "seil"
cask "viscosity"
