# Preview images. Doesn't work in tmux
set preview_images true
set preview_images_method sixel

# Set a title for the window?
set update_title true

# Set the title to "ranger" in the tmux program?
set update_tmux_title true

# Which colorscheme to use?  These colorschemes are available by default:
# default, jungle, snow, solarized
set colorscheme default

# Draw borders around columns?
# set draw_borders true
