[ui]
stylesets-dirs=~/.config/aerc/stylesets/
styleset-name=catppuccin-mocha
border-char-vertical=│
border-char-horizontal=─
mouse-enabled=true

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=elinks -dump -dump-color-mode 1
